[package]
name = "fibnacci-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
num = "0.4.2"

[[bin]]
name = "fib"
path = "src/main.rs"
